bigint
AlexeyShik/first-term pull request #4
Opened 2020-07-02 13:56 UTC by AlexeyShik

2020-07-02 20:29 UTC, kt-cpp requested changes
ну наверное это миноры

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.h
> +    std::vector <uint32_t> data;
правило хорошего тона: разделяешь данные, методы, константы + тайпдефы на разные блоки. в каждом блоке указываешь область видимости. например: private: bool, vector \n private: const BASe \n private: methods и тд.

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.h
> +    uint64_t static const BASE = static_cast<uint64_t>(UINT32_MAX) + 1;
static const type

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer& bitwise_operation(big_integer const& rhs, const std::function<uint32_t(uint32_t, __uint32_t)>&);
сделай using на этот тип function

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        auto sum = static_cast<uint64_t>(data[i]) + (i < rhs.size() ? rhs[i] : 0) + carry;
сделай какой-нибудь безопасный геттер для (i < rhs.size() ? rhs[i] : 0)

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        uint32_t curr = __builtin_popcount(digit);
сделай какой-нибудь метод для подсчета битиков, а туда уж вставь эту штуку

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    fill_back(std::max(static_cast<ptrdiff_t>(0), static_cast<ptrdiff_t>(rhs.size()) - static_cast<ptrdiff_t>(size())), 0);
мб лучше максимум в отдельной переменной посчитаешь тернарником?

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        data[i] = static_cast<uint32_t>(sub + ((borrow = (sub < 0)) ? BASE : 0));
лучше на несколько строк разбить

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return static_cast<uint32_t>(std::min(r3 / d2, static_cast<unsigned __int128>(BASE) - 1));
сделай using на 128 битный тип + такой каст в 32 битный не безопасен

2020-07-02 20:29 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        data[i + k] = static_cast<uint32_t>(diff % BASE);
у тебя же есть безопасный каст 64 в 32, почему здесь не оно?

2020-07-02 22:58 UTC, AlexeyShik commented on bigint/big_integer.h
> +    big_integer& bitwise_operation(big_integer const& rhs, const std::function<uint32_t(uint32_t, __uint32_t)>&);
``` C++
using func = std::function<uint32_t(uint32_t, __uint32_t)>;
```

2020-07-02 22:58 UTC, AlexeyShik commented on bigint/big_integer.cpp
> +        auto sum = static_cast<uint64_t>(data[i]) + (i < rhs.size() ? rhs[i] : 0) + carry;
``` C++
uint32_t get_kth(size_t k) const;
```

2020-07-02 22:58 UTC, AlexeyShik commented on bigint/big_integer.cpp
> +        uint32_t curr = __builtin_popcount(digit);
``` C++
static size_t bit_count(uint32_t a);
```

2020-07-02 22:58 UTC, AlexeyShik commented on bigint/big_integer.cpp
> +    fill_back(std::max(static_cast<ptrdiff_t>(0), static_cast<ptrdiff_t>(rhs.size()) - static_cast<ptrdiff_t>(size())), 0);
Даже if выглядит лучше, чем этот здоровенный тернарник с кастами
``` C++
if (rhs.size() > size()) {
    fill_back(rhs.size() - size(), 0);
}
```

2020-07-02 22:58 UTC, AlexeyShik commented on bigint/big_integer.cpp
> +        data[i] = static_cast<uint32_t>(sub + ((borrow = (sub < 0)) ? BASE : 0));
``` C++
borrow = sub < 0;
data[i] = static_cast<uint32_t>(sub + (borrow ? BASE : 0));
```

2020-07-02 22:58 UTC, AlexeyShik commented on bigint/big_integer.cpp
> +    return static_cast<uint32_t>(std::min(r3 / d2, static_cast<unsigned __int128>(BASE) - 1));
``` C++
using uint128_t = unsigned __int128;
```

``` C++
return low32_bits(std::min(r3 / d2, static_cast<uint128_t>(BASE - 1)));
```

2020-07-02 22:58 UTC, AlexeyShik commented on bigint/big_integer.cpp
> +        data[i + k] = static_cast<uint32_t>(diff % BASE);
``` C++
data[i + k] = low32_bits(diff);
```

2020-07-02 23:03 UTC, AlexeyShik commented on bigint/big_integer.h
> +    uint64_t static const BASE = static_cast<uint64_t>(UINT32_MAX) + 1;
``` C++
static const uint64_t BASE = static_cast<uint64_t>(UINT32_MAX) + 1;
```

2020-07-03 06:20 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer& bitwise_operation(big_integer const& rhs, const std::function<uint32_t(uint32_t, __uint32_t)>&);
кстати почему второй тип с подчеркиваниями?

2020-07-03 06:24 UTC, kt-cpp approved these changes

2020-07-03 06:24 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        const auto ans = big_integer::short_div(*this, static_cast<uint32_t>(rhs[0]));
каст лишний

2020-07-03 06:24 UTC, merged

2020-07-03 10:25 UTC, AlexeyShik commented on bigint/big_integer.h
> +    big_integer& bitwise_operation(big_integer const& rhs, const std::function<uint32_t(uint32_t, __uint32_t)>&);
Не специально, когда набираю uint32, clion почему-то именно его предлагает